---
- name: Check which vagrant plugins are installed.
  command: vagrant plugin list
  register: vagrant_plugins_list_result
  changed_when: false

- name: Install Vagrant plugins
  command: "vagrant plugin install {{ item }}"
  when:
    - "'vagrant' in homebrew_cask_apps"
    - (item not in vagrant_plugins_list_result.stdout) or vagrant_plugins_force_install|default(false)
  with_items: "{{ vagrant_plugins }}"
